MI.Web/Models/Inventories/InventoryDashboardViewModel.cs
using MI.Web.Data.Entities.InventorySection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Models.Inventories
{
    public class InventoryDashboardViewModel
    {
        public Inventory Inventory { get; set; }

        public IQueryable<Item> LastTenItemsAdded { get; set; }

        public IQueryable<Item> LastTenItemsModified { get; set; }

        public int ItemCount { get; set; }
    }
}

MI.Web/Models/Inventories/InventoryListViewModel.cs
using MI.Web.Data.Entities.InventorySection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Models.Inventories
{
    public class InventoryListViewModel
    {
        public IQueryable<Inventory> OwnedInventories { get; set; }

        public IQueryable<Inventory> InvitedInventories { get; set; }
    }
}

MI.Web/Models/Inventories/InventoryUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Models.Inventories
{
    public class InventoryUsersViewModel
    {
        public string UserId { get; set; }

        public string UserFullName { get; set; }

        public string UserEmail { get; set; }

        public string UserImagePath { get; set; }

        public int RoleId { get; set; }

        public string RoleName { get; set; }
    }
}

MI.Web/Models/Inventories/InventoryViewModel.cs
using MI.Web.Data.Entities.InventorySection;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Models.Inventories
{
    public class InventoryViewModel : Inventory
    {
        [Display(Name = "Responsável pelo Inventário")]
        public string OwnerID { get; set; }

        [Display(Name = "Imagem do Inventário")]
        public IFormFile ImageFile { get; set; }
    }
}

MI.Web/Models/Inventories/ItemViewModel.cs
using MI.Web.Data.Entities.InventorySection;
using MI.Web.Data.Interfaces;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Models.Inventories
{
    public class ItemViewModel : Item
    {
        [Display(Name="Imagem")]
        public IFormFile ImageFile { get; set; }

        public int BrandId { get; set; }
    }
}

MI.Web/Controllers/InventorySection/InventoriesController.cs
using MI.Common.JsonModels.Inventory;
using MI.Common.Models;
using MI.Web.Data.Entities.InventorySection;
using MI.Web.Data.Interfaces;
using MI.Web.Extensions;
using MI.Web.Helpers;
using MI.Web.Helpers.Interfaces;
using MI.Web.Models.Inventories;
using MI.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MI.Web.Controllers.InventorySection
{
    [Authorize]
    public class InventoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserHelper _userHelper;
        private readonly INotifyService _notifyService;
        private readonly IEmailSender _emailSender;

        public InventoriesController(IUnitOfWork unitOfWork, IUserHelper userHelper, INotifyService notifyService, IEmailSender emailSender)
        {
            _userHelper = userHelper;
            this._notifyService = notifyService;
            this._emailSender = emailSender;
            _unitOfWork = unitOfWork;
        }

        #region Index

        public async Task<IActionResult> Index()
        {
            this.ExpectingError();
            this.ExpectingSuccess();

            if (User.IsInRole("Superuser") || User.IsInRole("Admin"))
            {
                return View(new InventoryListViewModel()
                {
                    OwnedInventories = _unitOfWork.Inventories.GetAll()
                });
            }

            var inventories = new InventoryListViewModel()
            {
                InvitedInventories = _unitOfWork.Inventories.GetInventoriesUserIsInvited(User.GetUserId()),
                OwnedInventories = _unitOfWork.Inventories.GetInventoriesOwnedByUser(User.GetUserId())
            };

            return View(inventories);
        }

        public async Task<IActionResult> GetAllInformationFromInventory([FromRoute] Guid? id)
        {
            if (id == null)
            {
                return BadRequest(new Response
                {
                    IsSuccess = false,
                    Message = "Dados fornecidos incorretos"
                });
            }

            var inv = await _unitOfWork.Inventories.GetByUUIDAsync(id.Value.ToString());

            if (inv == null)
            {
                return NotFound(new Response
                {
                    IsSuccess = false,
                    Message = "Inventario não encontrado"
                });
            }

            if (inv.IsDisabled)
            {
                return NotFound(new Response
                {
                    IsSuccess = false,
                    Message = "Inventario não encontrado"
                });
            }

            if (User.IsInRole("User"))
            {
                if (await _unitOfWork.Inventories.GetUserRoleInInventoryAsync(User.GetUserId(), inv.Id) == null)
                {
                    return Forbid();
                }
            }

            return Ok(
                new Response()
                {
                    IsSuccess = true,
                    Result = new JsonInventoryFull()
                    {
                        Inventory = new JsonInventory()
                        {
                            IsDisabled = inv.IsDisabled,
                            LastModified = inv.LastModified,
                            UUId = inv.UUId,
                            Name = inv.Name
                        },

                        Items = _unitOfWork.Items
                            .GetItemsFromInventory(inv.Id)
                            .Select(item =>
                                new JsonItem
                                {
                                    IsDisabled = item.IsDisabled,
                                    LastModified = item.LastModified,
                                    InventoryUUId = inv.UUId,
                                    BrandUUId = item.Model.Brand.UUId,
                                    ModelUUId = item.Model.UUId,
                                    PlaceUUId = item.Place.UUId,
                                    TypeUUId = item.Type.UUId,
                                    ItemStateUUId = item.ItemState.UUId,
                                    UUId = item.UUId,
                                    Name = item.Name,
                                    Description = item.Description,
                                    ItemInput = item.ItemInput,
                                    ItemOutput = item.ItemOutput
                                }
                            ).ToList(),

                        ItemStates = _unitOfWork.ItemsStates
                            .GetItemStatesFromInventory(inv.Id)
                            .Select(state =>
                                new JsonItemState
                                {
                                    IsDisabled = state.IsDisabled,
                                    LastModified = state.LastModified,
                                    InventoryUUId = inv.UUId,
                                    UUId = state.UUId,
                                    State = state.State
                                }
                            )
                            .ToList(),

                        ItemTypes = _unitOfWork.ItemTypes
                            .GetItemTypesFromInventory(inv.Id)
                            .Select(type =>
                                new JsonItemType
                                {
                                    IsDisabled = type.IsDisabled,
                                    LastModified = type.LastModified,
                                    InventoryUUId = inv.UUId,
                                    UUId = type.UUId,
                                    Name = type.Name
                                }
                            )
                            .ToList(),

                        ItemPlaces = _unitOfWork.ItemPlaces
                            .GetItemPlacesFromInventory(inv.Id)
                            .Select(place =>
                                new JsonItemPlace
                                {
                                    IsDisabled = place.IsDisabled,
                                    LastModified = place.LastModified,
                                    InventoryUUId = inv.UUId,
                                    Name = place.Name,
                                    UUId = place.UUId
                                }
                            )
                            .ToList(),

                        ItemBrands = _unitOfWork.ItemBrands
                            .GetItemBrandsFromInventory(inv.Id)
                            .Select(brand =>
                                new JsonItemBrand
                                {
                                    UUId = brand.UUId,
                                    LastModified = brand.LastModified,
                                    IsDisabled = brand.IsDisabled,
                                    InventoryUUId = inv.UUId,
                                    Name = brand.Name
                                }
                            )
                            .ToList(),

                        ItemModels = _unitOfWork.ItemModels
                            .GetItemModelsFromInventory(inv.Id)
                            .Select(model =>
                                new JsonItemModel
                                {
                                    IsDisabled = model.IsDisabled,
                                    LastModified = model.LastModified,
                                    InventoryUUId = inv.UUId,
                                    BrandUUId = model.Brand.UUId,
                                    UUId = model.UUId,
                                    Name = model.Name
                                }
                            )
                            .ToList(),
                    }
                }
            );
        }

        #endregion

        #region Create

        public async Task<IActionResult> Create()
        {
            ViewData["UserList"] = _userHelper.GetAllUsers();

            return View(new InventoryViewModel());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(InventoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["UserList"] = _userHelper.GetAllUsers();

                return View(model);
            }

            if (User.IsInRole("Admin") || User.IsInRole("Superuser"))
            {
                if (model.OwnerID == Guid.Empty.ToString())
                {
                    ModelState.AddModelError(string.Empty, "Utilizador inválido.");

                    ViewData["UserList"] = _userHelper.GetAllUsers();

                    return View(model);
                }

                var userExists = await _userHelper.GetUserByIdAsync(model.OwnerID);
                if (userExists == null)
                {
                    ModelState.AddModelError(string.Empty, "Utilizador inválido.");

                    ViewData["UserList"] = _userHelper.GetAllUsers();

                    return View(model);
                }

                model.OwnerID = userExists.Id;
            }
            else
            {
                model.OwnerID = User.GetUserId();
            }

            var image = await FileHelper.SaveImage(model.ImageFile, "inventory");
            model.ImagePath = image.Result.ToString();

            var chkCreate = await _unitOfWork.Inventories.CreateForAsync(model, model.OwnerID);
            if (!chkCreate.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, "Erro inesperado.");

                ViewData["UserList"] = _userHelper.GetAllUsers();

MI.Web/Views/Inventory/Index.cshtml
@model MI.Web.Models.Inventories.InventoryDashboardViewModel
@{
    ViewData["Title"] = "Dashboard";
}

<h1>@Model.Inventory.Name</h1>
<h4>Item(s): @Model.ItemCount</h4>

<hr /><br/>

<h4>Últimos 10 items adicionados:</h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Type.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Place.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).ItemState.State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Model.Brand.Name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Model)
                </th>

                <th>
                    Saída do Item
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.LastTenItemsAdded)
            {
                <tr>
                    <td>
                        @if (!string.IsNullOrEmpty(item.ImagePath))
                        {
                            <img src="@Url.Content(item.ImagePath)" alt="imagem" style="width:100px;height:150px;max-width:100%;height:auto;" />
                        }
                        else
                        {
                            <img src="~/media/images/common/no_preview.jpg" alt="imagem" style="width:100px;height:150px;max-width:100%;height:auto;" />
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Place.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemState.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model.Name)
                    </td>
                    <td>
                        @if(item.ItemOutput != null)
                        {
                            <span>@item.ItemOutput.Value.ToShortDateString()</span>
                        }
                        else
                        {
                            <span>N/A</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
    
<hr />

<h4>Últimos 10 items modificados:</h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Type.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Place.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).ItemState.State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Model.Brand.Name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.LastTenItemsAdded.ElementAtOrDefault(0).Model)
                </th>

                <th>
                    Saída do Item
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.LastTenItemsModified)
            {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.ImagePath))
                    {
                        <img src="@Url.Content(item.ImagePath)" alt="imagem" style="width:100px;height:150px;max-width:100%;height:auto;" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Place.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemState.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model.Name)
                </td>
                <td>
                    @if (item.ItemOutput != null)
                    {
                        <span>@item.ItemOutput.Value.ToShortDateString()</span>
                    }
                    else
                    {
                        <span>N/A</span>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

MI.Web/Views/Inventory/_Layout.cshtml
@inject MI.Web.Data.Interfaces.IUnitOfWork unitOfWork
@{ 
    var inventoryId = this.ViewContext.RouteData.Values.GetValueOrDefault("inventoryId");
    if (inventoryId == null)
    {
        inventoryId = this.ViewContext.RouteData.Values.GetValueOrDefault("id");
    }
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - @await this.ViewContext.GetInventoryNameAsync(unitOfWork, inventoryId.ToString())</title>
    <link rel="icon" href="~/miicon.png" type="image/png" sizes="16x16">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/solid.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/solid.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Common.css" />
    <link rel="stylesheet" href="~/css/Enterprise.css" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/font-awesome/js/fontawesome.js"></script>
        <script src="~/lib/font-awesome/js/solid.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous">
        </script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous">
        </script>
        <script src="~/lib/font-awesome/js/fontawesome.min.js"></script>
        <script src="~/lib/font-awesome/js/solid.min.js"></script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <partial name="_LoadingPartial" />
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" id="topbar">

        <button id="sidebarBtn" class="btn d-print-none" type="button"><i class="fas fa-bars"></i>&nbsp;Menu&nbsp;<i class="fas fa-chevron-down"></i></button>

        <div id="companyBrand">
            <h2 class="mb-1">@await this.ViewContext.GetInventoryNameAsync(unitOfWork, inventoryId.ToString())</h2>
        </div>



        <div id="topbarPartial" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse flex-grow-0 d-print-none">
            <partial name="_loginPartial" />            
        </div>
    </nav>

    <div class="sidebar sidebar-collapse box-shadow d-print-none" id="sidebar" style="display:none;">
        <div class="p-2">
            <button type="button" class="btn w-100"><i class="fas fa-times"></i></button>
        </div>
        <hr />

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="Inventory"
                     asp-route-inventoryId="@inventoryId"
                     icon="user-tag" text="Home"
                     class="sidebar-button"></action-icon>

        <hr />

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="Items"
                     asp-route-inventoryId="@inventoryId"
                     icon="box-open" text="Items"
                     class="sidebar-button"></action-icon>

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="ItemStates"
                     asp-route-inventoryId="@inventoryId"
                     icon="file-alt" text="Tipos de Estado"
                     class="sidebar-button"></action-icon>

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="ItemTypes"
                     asp-route-inventoryId="@inventoryId"
                     icon="tags" text="Categorias"
                     class="sidebar-button"></action-icon>

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="ItemPlaces"
                     asp-route-inventoryId="@inventoryId"
                     icon="map-marker-alt" text="Localizações"
                     class="sidebar-button"></action-icon>

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="ItemBrands"
                     asp-route-inventoryId="@inventoryId"
                     icon="object-group" text="Marcas"
                     class="sidebar-button"></action-icon>

        <action-icon asp-route="inventoryHome"
                     asp-route-action="Index"
                     asp-route-controller="ItemModels"
                     asp-route-inventoryId="@inventoryId"
                     icon="cubes" text="Modelos"
                     class="sidebar-button"></action-icon>

        <action-icon asp-controller="Inventories"
                     asp-action="Users"
                     asp-route-id="@inventoryId"
                     class="sidebar-button"
                     text="Utilizadores" icon="users"></action-icon>

        <hr />

        <action-icon asp-route-action="Index"
                     asp-route-controller="Inventories"
                     icon="arrow-left" text="Sair"
                     class="sidebar-button"></action-icon>

        <div id="sideBarLogin" class="d-sm-none">
            <hr />
            <partial name="_loginPartial" />
        </div>
    </div>

    <main role="main" class="pl-3 pr-3 content">
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer class="footer d-print-none">
        <div class="container">
            &copy; 2019 - MultInventory Lite - Projecto Académico
        </div>
    </footer>

    <script type="text/javascript">
        window.addEventListener('load', () => {
            document.querySelector('#sidebar button').addEventListener('click', () => {
                document.querySelector('#sidebar').style.display = "none";
            });

            document.querySelector('#sidebarBtn').addEventListener('click', () => {
                document.querySelector('#sidebar').style.display = "block";
            });
        });


        function displayLoading() {
            $('.loading').show();
        }

        $(window).on('beforeunload', () => {
            displayLoading();
        });

        $(document).on('submit', 'form', () => {
            displayLoading();
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>